//
//  JaguarDefines.h
//  Jagemu
//
//  Created by Kate on 6/30/18.
//  Copyright © 2018 Luigi Thirty. All rights reserved.
//

#ifndef JaguarDefines_h
#define JaguarDefines_h

// NTSC: Video output is interlaced, so effectively 60fps.
#define FRAMES_PER_SECOND   29.97
#define FIELDS_PER_SECOND   60

#define ONE                 1
#define ONE_MICROSECOND     1000000

#define NTSC_REFRESH_RATE   FRAMES_PER_SECOND
#define NTSC_INTERLACE_RATE 60

#define LINES_PER_FRAME     525
#define HALFLINES_PER_FRAME 1050

#define USEC_PER_FRAME      60000000
#define USEC_PER_LINE       (ONE / NTSC_INTERLACE_RATE / LINES_PER_FRAME/2) * ONE_MICROSECOND
#define USEC_PER_HALFLINE   (ONE / NTSC_REFRESH_RATE / LINES_PER_FRAME) * ONE_MICROSECOND

/* Clocks */
#define CLOCK_NTSC      26590906
#define CLOCK_PAL       26593900
#define CLOCK_MASTER    CLOCK_NTSC

#define CLOCK_M68K      (CLOCK_MASTER/2)    // Runs at 1/2 the master clock speed
#define CLOCK_RISC      (CLOCK_NTSC)        // Runs at the master clock speed

#define VIDEO_CLOCKS_PER_FRAME  (CLOCK_MASTER / FRAMES_PER_SECOND)
#define RISC_CLOCKS_PER_FRAME   (CLOCK_MASTER / FRAMES_PER_SECOND)
#define CPU_CLOCKS_PER_FRAME    (CLOCK_M68K / FRAMES_PER_SECOND)

#define VIDEO_CLOCKS_PER_FIELD  (CLOCK_MASTER / FIELDS_PER_SECOND)
#define RISC_CLOCKS_PER_FIELD   (CLOCK_MASTER / FIELDS_PER_SECOND)
#define CPU_CLOCKS_PER_FIELD    (CLOCK_M68K / FIELDS_PER_SECOND)

#define VIDEO_CLOCKS_PER_LINE   (VIDEO_CLOCKS_PER_FRAME / LINES_PER_FRAME)
#define RISC_CLOCKS_PER_LINE    (RISC_CLOCKS_PER_FRAME / LINES_PER_FRAME)
#define CPU_CLOCKS_PER_LINE     (CPU_CLOCKS_PER_FRAME / LINES_PER_FRAME)

#define VIDEO_CLOCKS_PER_HALFLINE   (VIDEO_CLOCKS_PER_FIELD / HALFLINES_PER_FRAME)
#define RISC_CLOCKS_PER_HALFLINE    (RISC_CLOCKS_PER_FIELD / HALFLINES_PER_FRAME)
#define CPU_CLOCKS_PER_HALFLINE     (CPU_CLOCKS_PER_FIELD / HALFLINES_PER_FRAME)

#define MASTER_CLOCKS_PER_USEC  ( CLICK_MASTER / 1000000 )
#define CPU_CLOCKS_PER_USEC     ( CLOCK_M68K / 1000000 )

#define USEC_TO_M68K_CLOCKS(X)  ( X * CPU_CLOCKS_PER_USEC )

/* Types */
typedef uint32_t JAGPTR;

#endif /* JaguarDefines_h */
